### PR TITLE
Bump api version

### PR DESCRIPTION
**Pull request by zurk**
I need this fix https://github.com/src-d/lookout/issues/409
to make this PR work: https://github.com/src-d/style-analyzer/pull/562

### CODE REVIEW

**Comment by zurk** [comment]
Also, bump lookout-sdk-ml version

**Comment by vmarkovtsev** [comment]
@zurk you need to change the version in a few other places

**Comment by zurk** [comment]
@vmarkovtsev done

**Comment by zurk** [comment]
ok!
I think that if you update you package dependency to new `0.a+1.0` version, you should update yours with `0.b+1.0` too

**Pull request merged**
