### PR TITLE
Include load_file into the parse_files method

### PR DESCRIPTION
**Pull request by warenlg**
Signed-off-by: Waren Long <waren@sourced.tech>

I need this in order to remove `prepare_files` from `style-analyzer` and use `parse_files` instead

### CODE REVIEW

**Comment by warenlg** [comment]
This function should be used instead of `prepare_files` only, so in `general_report.py` and `noisy_quality_report.py` where there is no `File` preloaded, just a stream of filepaths. Yes, it's a bit tricky, sorry

**Comment by zurk** [comment]
ok. I think I am wrong because there is `filter_files` function for the analyzer. And `parse_files` is used for UAST parsing also. 
So, I am fine with `content_getter` removal but it looks like we should include `filter_files`  call from `parse_files`.

**Comment by warenlg** [comment]
Yes I also wanted to do it, but it is again tricky here because imagine we call `filter_files` at the beginning of `parse_files`, then we parse the list of files and we have a given number of files rejected due to parsing errors, we could be a lot below the `overall_size_limit` in theory.
If we don't care, I can do it like this anyway.

**Comment by zurk** [comment]
I agree it is a good optimization to do, but I think what is more important is to be able to reproduce the same data flow we have in the analyzer. And a lookout does all UAST-related work and it happens before our filters.

**Comment by vmarkovtsev** [comment]
@warenlg I guess you need a new sdk-ml release, right?

**Comment by warenlg** [comment]
Yes I do please

**Pull request merged**
